# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jschuste <jschuste@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/08 19:08:40 by jschuste          #+#    #+#              #
#    Updated: 2025/04/09 02:31:48 by jschuste         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libftprintf.a

# Compiler and flags
CC = cc
CFLAGS = -Wall -Wextra -Werror -c
INCLUDES = -Iincludes/

SRCS = src/ft_printf.c \
       ft_print_char.c \
       ft_print_string.c \
       ft_print_ptr.c \
       ft_print_int.c \
       ft_print_unsigned.c \
       ft_print_hex.c

OBJS = $(SRCS:.c=.o)

# Archive command
AR = ar rcs

# Build rule
all: $(NAME)

$(NAME): $(OBJS)
        @$(AR) $(NAME) $(OBJS)
        @echo "libftprintf.a created"

# Object file generation
%.o: %.c
        @$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
    rm -f $(OBJS)
    @echo "Object files removed"
fclean: clean
    rm -f $(NAME)
    @echo "libftprintf.a removed"

re: fclean all

.PHONY: all clean fclean re
